# Generated by Django 2.2.4 on 2019-08-03 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='startingDate',
            new_name='checkInDate',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkOutDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
