# Generated by Django 2.2.4 on 2019-08-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20190803_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
