# Generated by Django 2.2.4 on 2019-08-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190805_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('conf', 'confirmada'), ('cIn', 'checkin'), ('cOut', 'checkout'), ('canc', 'canceled')], default='conf', max_length=4),
        ),
    ]
