# Generated by Django 2.2.4 on 2019-08-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comments',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='creditCard',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='telephone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
