# Generated by Django 2.2.4 on 2019-08-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20190807_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='days',
        ),
    ]
